apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: tc1
  labels:
    app: foo
spec:
  replicas: 20
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      name: tc1
      labels:
        app: foo
        schedulerName: poseidon
    spec:
      schedulerName: poseidon
      containers:
      - name: 1testtask 
        image: "nginx:1.11.1-alpine"
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: basepodkey
                operator: In
                values:
                - basepodvalue
            topologyKey: kubernetes.io/hostname
