apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: basepod
  labels:
    basepodkey: basepodvalue
spec:
  replicas: 20
  selector:
    matchLabels:
      basepodkey: basepodvalue
  template:
    metadata:
      name: basepod
      labels:
        basepodkey: basepodvalue
        schedulerName: poseidon
    spec:
      schedulerName: poseidon
      containers:
      - name: benchmark
        image: "nginx:1.11.1-alpine"
      nodeSelector:
        key1: value1
