apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: tc22
  labels:
    app: foo
spec:
  replicas: 10
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      name: tc22
      labels:
        app: foo
        schedulerName: poseidon
    spec:
      schedulerName: poseidon
      containers:
      - name: testcase2task2
        image: "nginx:1.11.1-alpine"
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: basepodkey
                operator: NotIn
                values:
                - basepodvalue
            topologyKey: kubernetes.io/hostname
